apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-main
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 20102
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: main
